# Generated by Django 5.0.2 on 2024-03-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('purpose', models.CharField(max_length=255)),
                ('application_date', models.DateTimeField()),
                ('application_status', models.CharField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default='0', max_length=1)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.borrowers')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('term_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'active'), (1, 'closed')], default='0', max_length=1)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.borrowers')),
                ('loan_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan_applications')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Audit_Trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Approval_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'rejected'), (1, 'approved')], max_length=1)),
                ('comments', models.TextField()),
                ('approved_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Collaterals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('estimated_value', models.FloatField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
    ]
