# Generated by Django 5.0.2 on 2024-02-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_borrowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('purpose', models.CharField(max_length=255)),
                ('application_date', models.DateTimeField()),
                ('application_status', models.CharField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default='0', max_length=1)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.borrowers')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('term_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'active'), (1, 'closed')], default='0', max_length=1)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.borrowers')),
                ('loan_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loan_applications')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Repayment_Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.FloatField()),
                ('status', models.CharField(choices=[(0, 'pending'), (1, 'paid')], default='0', max_length=1)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.users')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Audit_Trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Approval_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'rejected'), (1, 'approved')], max_length=1)),
                ('comments', models.TextField()),
                ('approved_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.users')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Collaterals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('estimated_value', models.FloatField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Late_Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('late_fee', models.FloatField()),
                ('late_fee_paid_date', models.DateField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.loans')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.payments')),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.users')),
            ],
        ),
    ]
